### ISSUE TITLE
Find ways to improve build times.

### ISSUE THREAD

**Issue by anthonyshew** [kittrgg/kittr#375]
My build times in Github actions are atrocious. I don't cache anything ever and I'm sure the process can be vastly sped up.

**Comment by masonschafercodes** [comment]
easiest way to start caching is by using the built-in cache step from `actions/setup-node@v3`. 

Example:

```yml
- name: Setup Node.js
  uses: actions/setup-node@v3
  with:
    node-version: '16'
    cache: 'yarn'
```
